# Generated by Django 5.0.2 on 2024-02-18 01:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Documents Type',
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_card', models.CharField(max_length=20, verbose_name='identity_card')),
                ('first_name', models.CharField(max_length=60, verbose_name='first_name')),
                ('second_name', models.CharField(max_length=60, verbose_name='second_name')),
                ('surname', models.CharField(max_length=60, verbose_name='surname')),
                ('second_surname', models.CharField(max_length=60, verbose_name='second_surname')),
                ('cellphone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese solo números.', regex='^[0-9]+$')], verbose_name='cellphone')),
                ('professional_card', models.CharField(max_length=20, verbose_name='identity_card')),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
                ('date_update', models.DateTimeField(verbose_name='date_update')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_medics', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.documenttype', verbose_name='document_type')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_medics', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medic',
                'verbose_name_plural': 'Medics',
                'db_table': 'medic',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_card', models.CharField(max_length=20, verbose_name='identity_card')),
                ('first_name', models.CharField(max_length=60, verbose_name='first_name')),
                ('second_name', models.CharField(max_length=60, verbose_name='second_name')),
                ('surname', models.CharField(max_length=60, verbose_name='surname')),
                ('second_surname', models.CharField(max_length=60, verbose_name='second_surname')),
                ('birth_date', models.DateTimeField(verbose_name='birth_date')),
                ('cellphone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese solo números.', regex='^[0-9]+$')], verbose_name='cellphone')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('type', models.CharField(choices=[('POL', 'Poliza de Salud'), ('PBS', 'Plan de Beneficios en Salud'), ('PAR', 'Particular')], default='PBS', max_length=3)),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
                ('date_update', models.DateTimeField(verbose_name='date_update')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.documenttype', verbose_name='document_type')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_patients', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.AddConstraint(
            model_name='medic',
            constraint=models.UniqueConstraint(fields=('document_type', 'identity_card'), name='UQ_DOCUMENT_TYPE_IDENTITY_CARD_MEDIC'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('document_type', 'identity_card'), name='UQ_DOCUMENT_TYPE_IDENTITY_CARD'),
        ),
    ]
