# Generated by Django 5.0.2 on 2024-02-18 02:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='medic',
            options={'verbose_name': 'Medico', 'verbose_name_plural': 'Medicos'},
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='cellphone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese solo números.', regex='^[0-9]+$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_medics', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='date_created',
            field=models.DateTimeField(verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='date_update',
            field=models.DateTimeField(verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='identity_card',
            field=models.CharField(max_length=20, verbose_name='Número de Identificación'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='professional_card',
            field=models.CharField(max_length=20, verbose_name='Tarjeta Profesional'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='second_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='second_surname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='surname',
            field=models.CharField(max_length=60, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_medics', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Inicio de Sesión'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identity_card',
            field=models.CharField(max_length=20, verbose_name='Número de Identificacion'),
        ),
    ]
