# Generated by Django 4.2.10 on 2024-02-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patient_full_name_alter_medic_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medic',
            name='user',
        ),
        migrations.AlterField(
            model_name='medic',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
    ]
