# Generated by Django 4.2.10 on 2024-02-18 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0004_remove_medic_user_alter_medic_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_patients', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
    ]
