# Generated by Django 4.2.10 on 2024-02-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_patient_birth_date_alter_patient_cellphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='full_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Nombre Completo'),
        ),
    ]
