# Generated by Django 4.2.10 on 2024-02-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_medic_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
