# Generated by Django 4.2.10 on 2024-02-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_medic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
